[tool.poetry]
name = "my-bedtimes"
version = "0.1.0"
description = ""
authors = ["Judah <i460958@FontysICT.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
